---
- hosts: imageservers
  become: yes
  become_user: isucon
  gather_facts: no
  tasks:
    - git:
        repo=https://github.com/tagomoris/xbuild.git
        dest=/home/isucon/.xbuild
        update=yes
        force=yes
    # ruby
    - command: /home/isucon/.xbuild/ruby-install 2.3.8 /home/isucon/.local/ruby
      args:
        creates: /home/isucon/.local/ruby/bin/ruby

- hosts: imageservers
  become: yes
  gather_facts: no
  tasks:
    # java
    - apt: name=openjdk-8-jdk state=present
