---
- hosts: imageservers
  become: yes
  become_user: isucon
  gather_facts: no
  tasks:
    - git:
        repo=https://github.com/tagomoris/xbuild.git
        dest=/home/isucon/.xbuild
        update=yes
        force=yes
    # https://twitter.com/matsuu/status/773105183744069633
    - replace: dest=/home/isucon/.xbuild/perl-install regexp='http://cpanmin\.us/' replace='http://git.io/cpanm'

- hosts: imageservers
  become: yes
  gather_facts: no
  tasks:
    # java
    - apt: name=openjdk-8-jdk state=present
