---
- hosts: imageservers
  gather_facts: no
  become: yes
  become_user: isucon
  tasks:
    - git:
        repo=https://github.com/isucon/isucon5-qualify.git
        dest=/tmp/isucon5-qualify
    - command: rsync -avz --delete /tmp/isucon5-qualify/webapp /home/isucon/
    # /home/isucon/webapp/{etc,go,java,nodejs,perl,php,python,ruby,scala,sql,static}
    - command: rm -rf /tmp/isucon5-qualify
      args:
        removes: /tmp/isucon5-qualify
    - name: fix isucon user
      replace:
        dest: /home/isucon/webapp/java/src/main/resources/application.properties
        regexp: 'ISUCON5_DB_USER:root'
        replace: 'ISUCON5_DB_USER:isucon'
    - name: fix isucon password
      replace:
        dest: /home/isucon/webapp/java/src/main/resources/application.properties
        regexp: 'ISUCON5_DB_PASSWORD:'
        replace: 'ISUCON5_DB_PASSWORD:isucon'
    - name: java
      shell: ./mvnw package
      args:
        chdir: /home/isucon/webapp/java

  # post_tasks:
    # - command: sudo su - isucon /home/isucon/init.sh

- hosts: imageservers
  become: yes
  gather_facts: no
  tasks:
    - copy: src=../files/env.sh dest=/home/isucon/env.sh owner=isucon mode=644
    - name: java (systemd)
      copy: src=../files/systemd.java.service dest=/etc/systemd/system/isuxi.java.service owner=root mode=644

    - name: default application selection
      service: name=isuxi.java state=started enabled=true
