---
- hosts: benchservers
  become: yes
  become_user: isucon
  gather_facts: no
  tasks:
    - git:
        repo=https://github.com/tagomoris/xbuild.git
        dest=/home/isucon/.xbuild
        update=yes

- hosts: benchservers
  become: yes
  gather_facts: no
  tasks:
    # java
    - apt: name=openjdk-8-jdk state=present
    # gradle
    - apt: name=gradle state=present
